### ISSUE TITLE
Compilation without modules fails.

### ISSUE THREAD

**Issue by luigifcruz** [nvidia-holoscan/holoscan-sdk#11]
I tried to disable the compilation of modules by passing `HOLOSCAN_BUILD_MODULES=OFF` but the configuration failed because CMake couldn't find `holoviz`. Looks like these modules are hard coded on multiple locations inside the code ([1](https://github.com/nvidia-holoscan/holoscan-sdk/blob/bb60fb787dd9c3b5f74bf7e36f9f4a159ff857ca/CMakeLists.txt#L168-L169), [2](https://github.com/nvidia-holoscan/holoscan-sdk/blob/bb60fb787dd9c3b5f74bf7e36f9f4a159ff857ca/CMakeLists.txt#L359-L360)).

```
CMake Error at CMakeLists.txt:196 (install):
  install TARGETS given target "holoviz" which does not exist.
```

Further errors are encountered after fixing the problems above.

Also, support for partial module installations would be useful for deployments that don't require all features. For example, would be cool if I could install Holoviz with TensorRT for inference without being forced to install ONNX Runtime.

**Comment by tbirdso** [comment]
After further discussion we've determined that the `HOLOSCAN_BUILD_MODULES` option was removed in Holoscan SDK v0.6.0.
