### ISSUE TITLE
Out-of-place GLFW dependency.

### ISSUE THREAD

**Issue by luigifcruz** [nvidia-holoscan/holoscan-sdk#12]
Looks like the GLFW dependency [is being listed](https://github.com/nvidia-holoscan/holoscan-sdk/blob/bb60fb787dd9c3b5f74bf7e36f9f4a159ff857ca/CMakeLists.txt#L191) as an install target for the core Holoscan application. Wouldn't this dependency belong to the `holoviz` module?

**Comment by jjomier** [comment]
Thanks for pointing this out. We are going to looking into fixing this.

**Comment by jjomier** [comment]
GLFW is not compiled statically and a dependency of HoloViz.
