### ISSUE TITLE
Windows 11 install holoscan 0.6  fail,only have 0.0.0.post1 version?

### ISSUE THREAD

**Issue by RuiLvCOMCEO** [nvidia-holoscan/holoscan-sdk#13]

**Comment by jjomier** [comment]
Can you describe how you install?

**Comment by agirault** [comment]
There is no windows wheels available, we only support Linux at this time.

**Comment by tbirdso** [comment]
Closing this issue as not currently supported in 1.0.3. Please refer to the [Holoscan SDK User Guide](https://docs.nvidia.com/holoscan/sdk-user-guide/getting_started.html#choose-your-platform) for details on supported platforms.
