### ISSUE TITLE
[ENH] `Parameter` type should be formattable.

### ISSUE THREAD

**Issue by luigifcruz** [nvidia-holoscan/holoscan-sdk#19]
It would be nice for the `Parameter<...>` type to also be formattable by the `HOLOSCAN_LOG_XXX` method. Currently, it's necessary to add a `param.get()` to make it work. A simple `fmtlib` format class for `Parameter` would suffice here.

**Comment by grlee77** [comment]
Thank you for the nice suggestion @luigifcruz! I will bring it up with the team for possible inclusion in a future release.

**Comment by grlee77** [comment]
Hi @luigifcruz, this suggestion was implemented in the recent v2.1 release. You can format `Parameter` without explicitly calling `get()` first when using `fmt::format` or the various `HOLOSCAN_LOG_INFO`, etc. logging functions.
