### ISSUE TITLE
Question - how to change the scheduler using holoscan api

### ISSUE THREAD

**Issue by itayzafrir** [nvidia-holoscan/holoscan-sdk#3]
Hi,
Using the holoscan api, how can we change the default scheduler. I see how it's done in the gxf layer (using yaml configuration) but how can this be done at the holoscan api level?

Purpose is to connect a clock to the scheduler and then to connect that clock to the gxf job statistics component. Is there a better way to use the job statistics gxf extension (from a holoscan application)?

Thanks

**Comment by jjomier** [comment]
Sorry for the late reply. In Holoscan SDK 0.5the scheduler is hard coded so you cannot change its behavior without modifying the SDK source. However we plan to introduce new schedulers in v0.6 along with an API.
