### ISSUE TITLE
Does holoscan-sdk support GPUs with Kepler architecture (e.g. NVIDIA Quadro K4000)?

### ISSUE THREAD

**Issue by mxochicale** [nvidia-holoscan/holoscan-sdk#33]
## Please describe your question
We are trying to use holoscan-sdk with a machine with NVIDIA Quadro K4000 (Kepler architecture). We wonder if holoscan-sdk support GPUs with Kepler architecture? It would be great if you share steps on what we can do in the case that Kepler architecture is not supported.

Thanks, Miguel

**Comment by tbirdso** [comment]
Hi @mxochicale , thanks for reaching out. We do not support Kepler architecture in Holoscan SDK testing at this time. For alternatives please refer to the [Holoscan SDK user guide](https://docs.nvidia.com/holoscan/sdk-user-guide/sdk_installation.html#sd-tab-item-2) for discrete GPU and driver requirements.
