### ISSUE TITLE
About SDK manager installation

### ISSUE THREAD

**Issue by ocean0922** [nvidia-holoscan/holoscan-sdk#6]
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'sdkmanager:amd64' instead of './sdkmanager_1.9.2-10888_amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 sdkmanager:amd64 : Depends: libgconf-2-4:amd64 but it is not installable
                    Depends: libcanberra-gtk-module:amd64 but it is not installable
                    Depends: locales:amd64 but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by jjomier** [comment]
Which OS are you trying to run sdkmanager on? You can verify the compatibility here: https://developer.nvidia.com/sdk-manager

**Comment by jjomier** [comment]
Feel free to submit follow up question on the [Holoscan forum](https://forums.developer.nvidia.com/c/healthcare/holoscan-sdk/320/none). Thank you!
